#!/bin/sh
set -eu
SUPABASE_URL_VALUE="\${SUPABASE_URL:-}"
SUPABASE_KEY_VALUE="\${SUPABASE_PUBLISHABLE_KEY:-}"
INTERNAL_DOMAIN_VALUE="\${INTERNAL_EMAIL_DOMAIN:-internal.agenzi.local}"
cat > /usr/share/nginx/html/config.js <<EOF
window.AGENZI_CONFIG={SUPABASE_URL:"\${SUPABASE_URL_VALUE}",SUPABASE_PUBLISHABLE_KEY:"\${SUPABASE_KEY_VALUE}",INTERNAL_EMAIL_DOMAIN:"\${INTERNAL_DOMAIN_VALUE}",APP_NAME:"AGENZI Studio",APP_SUBTITLE:"Internal Content OS"};
EOF
exec nginx -g "daemon off;"
