import{isConfigured,supabase}from'./supabase.js';import{state,signIn,signOut,loadSession,isAdmin,canManageClients,canManageTeam}from'./auth.js';import*as db from'./db.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],STATUS=['Draft','In Progress','Review Design','Revisi','Disetujui','Siap Posting','Posted'],PLAT=['Instagram','TikTok','Facebook','YouTube','LinkedIn','Threads'],ROLES={admin:'Admin',strategist:'Strategist',copywriter:'Copywriter',designer:'Designer'};
let D={clients:[],content:[],tasks:[],team:[],assignments:[],activity:[]},live=null,month=new Date().toISOString().slice(0,7),f={client:'',platform:'',status:'',search:''};
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m])),pf=c=>Array.isArray(c?.performance_metrics)?(c.performance_metrics[0]||{}):(c?.performance_metrics||{}),fmt=n=>Number(n||0).toLocaleString('id-ID');
const badge=v=>'<span class="badge '+(['Posted','Disetujui','Siap Posting','Done','Work','Active'].includes(v)?'ok':['Draft','In Progress','Review Design','Pending','Urgent'].includes(v)?'wait':v==='Not Work'?'bad':'neutral')+'">'+esc(v)+'</span>';
function toast(m,t='success'){const x=document.createElement('div');x.className='toast '+t;x.textContent=m;$('#toastRoot').append(x);setTimeout(()=>x.remove(),3000)}
function role(){return state.profile?.role||''}const currentView=()=>$('.view.active')?.id?.replace('view-','')||'dashboard';function isManager(){return ['admin','strategist'].includes(role())}
function renderNav(){const items=[['dashboard','Overview'],['calendar','Calendar'],['content','Content'],['tasks','My Tasks'],['analytics','Analytics'],['clients','Clients']];if(isAdmin())items.push(['team','Team & Access']);$('#nav').innerHTML=items.map(x=>'<button data-v="'+x[0]+'">'+x[1]+'</button>').join('');$('[data-v]').forEach(b=>b.onclick=()=>go(b.dataset.v))}
async function go(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v).classList.add('active');const n=([['dashboard','Overview'],['calendar','Calendar'],['content','Content'],['tasks','My Tasks'],['analytics','Analytics'],['clients','Clients'],['team','Team & Access']].find(x=>x[0]===v)||[])[1]||'Overview';$('#topTitle').textContent=n;$('#breadcrumb').textContent='AGENZI / '+n;$$('[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===v));try{if(v==='dashboard')dashboard();if(v==='calendar')calendar();if(v==='content')content();if(v==='tasks')tasks();if(v==='analytics')analytics();if(v==='clients')clientsPage();if(v==='team')teamPage()}catch(e){toast(e.message,'error')}}
async function refresh(){D.clients=await db.assignments();D.content=await db.content();D.tasks=await db.tasks();D.team=canManageTeam()?await db.team():[];D.assignments=canManageTeam()?await db.assignmentList():[];D.activity=await db.activity(20);$('#loginClientStat').textContent=D.clients.length||'20+'}
function activate(){ $('#boot').hidden=true;$('#loginScreen').hidden=true;$('#app').hidden=false;$('#userName').textContent=state.profile.full_name;$('#userRole').textContent=ROLES[role()]||role();$('#userAvatar').textContent=state.profile.full_name.slice(0,1).toUpperCase();$('#workspaceStatus').textContent='Connected';$('#quickAddButton').style.display='';renderNav();go('dashboard')}
function startLive(){if(live)live();live=db.realtime(async()=>{try{await refresh();await go($('.view.active')?.id.replace('view-','')||'dashboard')}catch(e){console.warn(e)}})}
function dashboard(){const ev=D.content.filter(c=>c.work_label!=='Not Evaluated'),w=ev.filter(c=>c.work_label==='Work'),today=new Date().toISOString().slice(0,10),over=D.tasks.filter(t=>t.due_date&&t.due_date<today&&t.status!=='Done').length;$('#view-dashboard').innerHTML='<div class="notice success"><b>Shared workspace</b> · Supabase Auth + Realtime.</div><h1>Good work, team.</h1><p class="subtitle">Satu workspace untuk 20+ client.</p><div class="hero"><div class="eyebrow">INTERNAL CONTENT OS</div><h2>Clarity for every handoff.</h2><p>Brief, copy, design, approval, publish, performance dan learning dalam satu alur.</p><div class="actions"><button class="button button-primary" id="dashCal">Open Calendar</button><button class="button" id="dashAna">View Analytics</button></div></div><div class="grid g4" style="margin-top:14px"><div class="card"><h3>Clients</h3><div class="metric">'+D.clients.length+'</div></div><div class="card"><h3>Content</h3><div class="metric">'+D.content.filter(c=>(c.content_date||'').startsWith(month)).length+'</div></div><div class="card"><h3>Attention</h3><div class="metric">'+(D.content.filter(c=>c.approval==='Pending').length+over)+'</div></div><div class="card"><h3>Work Rate</h3><div class="metric">'+(ev.length?Math.round(w.length/ev.length*100):0)+'%</div></div></div><div class="grid g2" style="margin-top:14px"><div class="card"><div class="card-header"><h3>Recent Content</h3></div><div class="tablewrap"><table class="table"><thead><tr><th>Content</th><th>Client</th><th>Status</th></tr></thead><tbody>'+D.content.slice(-7).reverse().map(c=>'<tr><td>'+esc(c.title)+'</td><td>'+esc(c.clients?.name||'')+'</td><td>'+badge(c.status)+'</td></tr>').join('')+'</tbody></table></div></div><div class="card"><div class="card-header"><h3>Activity</h3><span class="pill">Realtime</span></div><div class="log">'+D.activity.slice(0,8).map(a=>'<div class="log-item"><b>'+esc(a.action)+'</b><span>'+new Date(a.created_at).toLocaleString('id-ID')+'</span></div>').join('')+'</div></div></div>';$('#dashCal').onclick=()=>go('calendar');$('#dashAna').onclick=()=>go('analytics')}
